version: '3.8'

services:
  mautic-db:
    image: mariadb:10.6
    container_name: mautic-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mautic
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=mautic
    volumes:
      - /opt/mautic/db:/var/lib/mysql

  mautic:
    image: mautic/mautic:latest
    container_name: mautic
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - MAUTIC_DB_HOST=mautic-db
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mautic
      - MAUTIC_DB_NAME=mautic
    volumes:
      - /opt/mautic/html:/var/www/html
    depends_on:
      - mautic-db
