version: '3.8'

services:
  ark-server:
    image: mschnitzer/asa-linux-server:latest
    container_name: ark-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27016:27016/udp"
    environment:
      - GAME_PORT=7777
      - QUERY_PORT=27016
      - RCON_PORT=27020
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=adminpass
    volumes:
      - ark_data:/ark

volumes:
  ark_data:
