version: '3.8'

services:
  coolify:
    image: coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    ports:
      - "8003:8000"
    volumes:
      - /opt/coolify/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
